export {
	createMediaServerClient,
	MediaServerRequestError,
	type FetchLike,
	type MediaServerClient,
	type MediaServerClientOptions,
	type PaginationQuery,
	type LibraryScanOptions,
	type SearchQuery
} from './client';
export {
	abortedError,
	httpError,
	isMediaServerError,
	networkError,
	schemaError,
	type MediaServerError,
	type MediaServerErrorKind
} from './errors';
export {
	albumPageSchema,
	albumSchema,
	albumMetadataFormSchema,
	albumMetadataPatchSchema,
	albumPatchResponseSchema,
	artistPageSchema,
	artistSchema,
	connectFormSchema,
	errorBodySchema,
	historyItemSchema,
	historyPageSchema,
	libraryStatusSchema,
	pageEnvelopeSchema,
	pingResponseSchema,
	playlistPageSchema,
	playlistSchema,
	playlistNameBodySchema,
	playlistTracksBodySchema,
	searchResponseSchema,
	trackMetadataFormSchema,
	trackMetadataPatchSchema,
	trackPageSchema,
	trackSchema,
	type Album,
	type AlbumMetadataForm,
	type AlbumMetadataPatch,
	type AlbumPage,
	type AlbumPatchResponse,
	type Artist,
	type ArtistPage,
	type ConnectForm,
	type ErrorBody,
	type HistoryItem,
	type HistoryPage,
	type LibraryStatus,
	type PageEnvelope,
	type PingResponse,
	type Playlist,
	type PlaylistNameBody,
	type PlaylistPage,
	type PlaylistTracksBody,
	type SearchResponse,
	type Track,
	type TrackMetadataForm,
	type TrackMetadataPatch,
	type TrackPage
} from './schemas';
export { apiUrl, BaseUrlError, coverUrl, normalizeBaseUrl, streamUrl } from './url';
